# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "Renv" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "aiida" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "desktop" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "matlab" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "python-minimal-streamlit" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "qgis" 
    schedule:
      interval: "weekly"
